### ISSUE TITLE
Why the components are called twice?

### ISSUE THREAD

**Issue by jinserk** [NoahZinsmeister/web3-react#15] opened 2019-04-17 18:59 UTC
Hi @NoahZinsmeister!

This is very basic questions to understand how your library and the React operate; when I run the components, the subcomponents wrapped with `Web3Provider` called twice:
```
import React, { Fragment, useState, useEffect } from "react";
import Web3Provider, { Connectors, useWeb3Context } from "web3-react";

import './App.css';
import { Web3Unavailable, AccountUnavailable } from "./Error";
import NetworkInfo from "./NetworkInfo";
import AccountInfo from "./AccountInfo";

const { InjectedConnector } = Connectors;
const MetaMask = new InjectedConnector();
const connectors = { MetaMask };

function MyComponent() {
  const context = useWeb3Context();

  const checkSigner = () => {
    return context.library.getSigner(context.account);
  }
  const [signer, setSigner] = useState(checkSigner());

  useEffect(() => {
    setSigner(checkSigner());
  }, [context]);

  const myContext = {
    ...context,
    signer: signer
  }
  console.log(myContext);

  return (
    context.account ? (
      <Fragment>
        {/*
        <NetworkInfo context={myContext}/>
        <br />
        <AccountInfo context={myContext} />
        */}
      </Fragment>
    ) : <AccountUnavailable />
  );
}

function MetaMaskComponent() {
  const context = useWeb3Context();

  useEffect(() => {
    context.active || context.setConnector("MetaMask");
    console.log("MetaMaskComponent");
  }, [context]);

  return (context.active ? <MyComponent /> : <Web3Unavailable />);
}

export default function App() {
  return (
    <Web3Provider connectors={connectors} libraryName="ethers.js">
      <div className="App">
        <MetaMaskComponent />
      </div>
    </Web3Provider>
  );
}
```
![image](https://user-images.githubusercontent.com/823222/56313653-196e8800-6121-11e9-94b7-af00d21ca1ab.png)

As you can see, the console msg `MetaMaskComponent` called twice even though there is no change of `context`. I don't know well about the React's rendering and the hooks when `useEffect()` is executed. Could you help me to understand it?

**Comment by NoahZinsmeister** [comment] 2019-04-17 19:02
Yeah I noticed this earlier and am working on a fix as we speak :) should be out today or tomorrow! Once it lands, happy to explain how the mechanism works

**Comment by jinserk** [comment] 2019-04-17 19:04
Thank you so much!!

**Comment by NoahZinsmeister** [comment] 2019-04-17 21:41
Ok @jinserk should be fixed in 4.0.3 (@latest), please let me know if you're still having issues! Sorry about the problem, it's because I was memoizing some of the manager functions, which were causing a re-render _after_ certain state transitions.

**Comment by jinserk** [comment] 2019-04-18 04:04
I tested 4.0.3 and have still the same issue. When I check the `context.active`, it changes from `false` at the first console msg to `true` at the second one. However, when I get a log from `MyComponent`, the `myContext.active = true` at the both msgs. I guess the `context.setConnector` call is behind the first rendering in `MetaMaskComponent`, and this triggers second `useEffect()` call since `context` has been changed. So what my question is, do we have any hook before rendering in a component?

**Comment by NoahZinsmeister** [comment] 2019-04-18 04:11
that shouldn't be happening, sorry :/

i will take a look at this tomorrow. by the way, reproductions in a codesandbox are far easier for me to work with than copy-pasted code.

**Comment by jinserk** [comment] 2019-04-18 10:28
I added my code snippets in codesandbox (https://codesandbox.io/s/rjwjmronr4).

**Comment by NoahZinsmeister** [comment] 2019-04-18 14:50
Ok, this isn't happening because of web3-react. You're using a `useEffect` that takes the context in the dependency array, so `<MyComponent>` gets called twice, once on the initial context update, and once after the useEffect triggers to update the `signer` state variable. I've also pasted code below which is a clearer way of doing what you're trying to do.

```
  const [signer, setSigner] = useState();

  useEffect(() => {
    if (context.library) {
      setSigner(context.library.getSigner(context.account))
    }
  }, [context.library])
```

Re. MetaMask, after logging out and logging back in, if you want to spam your users it can be as simple as:

```
  useEffect(() => {
    if (!context.active) {
      context.setConnector('metaMask')
    }
  }, [context.active])
```

If they reject the connection attempt though then your app will hang, which is maybe why you should consider other patterns like a re-connect button, or something like that.

**Comment by jinserk** [comment] 2019-04-18 15:24
Got it. I updated your code to use `useRef` instead `useState` since it's still trigger re-rendering:
```
  const signer = useRef();

  useEffect(() => {
    if (context.library) {
      signer.current = context.library.getSigner(context.account);
    }
  }, [context.library]);
```
and confirmed that it works as what I expected with 4.0.3. Thanks a lot for your help!!

**Closed** 2019-04-18 15:24 UTC
