### ISSUE TITLE
Bug! Failed to disconnect user

### ISSUE THREAD

**Issue by pauloreis7** [NoahZinsmeister/web3-react#382] opened 2022-01-24 00:12 UTC
**Bug Description**

When using the deactivate function provided by the context we get a critical error saying that connector.off() is not a function. The issue comes from the EventEmitter implemented by AbstractConnector not always being a real EventEmitter.

I managed to solve this problem by installing the most recent events package and that solved the issue, but it is very important that this bug is solved either by handling the AbstractConnector event call better, thus ensuring that EventEmitter always exists or the events package is installed automatically by the web3-react dependencies to work well with events.

It could also be a workaround to document the necessity of installing the events package so that the user is informed about the necessity of the installation and does not have problems with events.

**Comment by elreco** [comment] 2022-02-05 23:52
I can't disconnect with the v8 too :'( it doesn't work

**Comment by DucSilva** [comment] 2022-02-10 10:42
> I can't disconnect with the v8 too :'( it doesn't work
> 
> It doesn't work on the example app too : https://web3-react-mu.vercel.app/
> 
> When you refresh the page, it's still connected to the wallet
the same for me with v10

**Comment by Funst3r** [comment] 2022-02-13 11:33
Does anyone has a workaround? I can’t deploy since the users aren’t able to switch or disconnect their wallets

**Comment by NoahZinsmeister** [comment] 2022-02-24 22:47
the "auto-connect" logic in the connectors is intentional, removing e.g. this line will change this behavior: https://github.com/NoahZinsmeister/web3-react/blob/main/packages/example/components/connectors/MetaMaskCard.tsx#L24

you should always be able to disconnect in v8 by calling `deactivate`

going to close this, feel free to open other issues with specific, reproducible bugs!

**Closed by NoahZinsmeister** 2022-02-24 22:47 UTC
Labels: v6
