### ISSUE TITLE
Cannot find module '@web3-react/walletconnect-connector' or its corresponding type declarations. After installing package

### ISSUE THREAD

**Issue by MahmoudThePeltist** [NoahZinsmeister/web3-react#302] opened 2021-10-22 20:47 UTC
Installing `@web3-react/walletconnect-connector`, succeeds but the web3installed are empty 
![image](https://user-images.githubusercontent.com/35870737/138520573-5b6c8e12-c030-4c4b-b268-5cce95d12040.png)

Steps to reproduce:
1. npm install @web3-react/walletconnect-connector
2. check directory, or import wallet connect package

**Expected Behavior**
For it to install the full package
![image](https://user-images.githubusercontent.com/35870737/138520731-cdfde256-82eb-4d17-83d9-5bb1074874cd.png)

**Comment by paulrberg** [comment] 2021-11-03 22:45
Duplicate of #297. Should be closed.

**Closed** 2022-01-11 21:35 UTC
Labels: bug
