### ISSUE TITLE
Localhost InjectedConnector activation problem

### ISSUE THREAD

**Issue by macor161** [NoahZinsmeister/web3-react#86] opened 2020-03-24 00:27 UTC
**Bug Description**

Activation of a `InjectedConnector` is currently failing when connected on localhost. It throws the following error:

<img width="632" alt="Screen Shot 2020-03-23 at 8 21 20 PM" src="https://user-images.githubusercontent.com/642515/77375594-59cc8200-6d44-11ea-9310-5ca24150322f.png">

**Reproduction**
Using the original [CodeSandbox](https://codesandbox.io/s/r7wymqkzwn) example from the [npm page](https://www.npmjs.com/package/web3-react).

Steps to reproduce:
1. Start a ganache server
2. Select localhost:8545 in Metamask
3. Click "activate injected"

**Additional Context**

Using Google Chrome on Mac

**Comment by benjlevesque** [comment] 2020-04-02 15:19
I have the same issue on my app, it throws an error connecting to ganache locally.

I believe the problem is that Metmask returns `0xNaN` for a private network, and web3-react [expects a number](https://github.com/NoahZinsmeister/web3-react/blob/v6/packages/core/src/normalizers.ts#L13)

**Comment by aaryamannchallani** [comment] 2020-06-29 20:36
I'm having a similar issue, 
`Unsupported chain id: 1337. Supported chain ids are: 1,3,5,52,...`
is getting thrown as an error if im connecting it to a local ganache instance,
but when select i select mainnet, then the local ganache network it works
i can provide video evidence if you email me

**Comment by treeder** [comment] 2020-07-22 19:54
Same issue here. I've also had Metamask return a "loading" chainId. This lib should probably ignore those and not emit the events or something.

![Screenshot 2020-07-20 at 3 06 04 PM](https://user-images.githubusercontent.com/75826/88222161-8da4af00-cc33-11ea-991b-4c6a14df75b2.png)

**Comment by jellydn** [comment] 2020-12-30 08:52
Hi there,

I came to cross this issue and make it works on localhost with ganache by below configuration. Hope you find it useful. Thanks.

```
// 1337 is default chainId from ganache
export const injected = new InjectedConnector({ supportedChainIds: [1, 3, 4, 5, 42, 56, 97, 1337] });

export const network = new NetworkConnector({
  urls: {
    1337: 'http://localhost:8545',
  },
  defaultChainId: 1,
});
```

**Comment by maze-maze-maze** [comment] 2021-06-16 20:37
I was able to work around this issue by configuring Ganache to return chainId 1 as used in mainnet by adding a flag to the command line and adjusting the custom network config in MetaMask to also have Chain ID 1


`ganache-cli --chainId 1 [remaining options]`

![image](https://user-images.githubusercontent.com/72437361/122289668-99870880-ceb8-11eb-90fc-fc1c3bce391b.png)

**Comment by NoahZinsmeister** [comment] 2022-01-11 20:58
hi! library author here, sorry for the (extremely) slow responses; for an update on the state of this library, please see https://github.com/NoahZinsmeister/web3-react/issues/163#issuecomment-1010210571

TLDR: v6 is deprecated and going into maintenance mode. i expect not to make any non-security related changes going forward (however, you're always welcome to! the beauty of open source)

i'll be closing a lot of issues with this message right now, but please feel free to re-open if you think the topic is still relevant!

thanks for using web3-react <3

**Closed by NoahZinsmeister** 2022-01-11 20:58 UTC
Labels: bug
