### ISSUE TITLE
Why does Uniswap use custom NetworkOnlyConnector and InjectedConnector rather than the ones from this lib?

### ISSUE THREAD

**Issue by pcowgill** [NoahZinsmeister/web3-react#46] opened 2019-11-06 15:01 UTC
Why does Uniswap (a high-profile example use case for this library) use custom `NetworkOnlyConnector` and `InjectedConnector` connectors rather than the ones from this lib?

[exported connectors from `web3-react` including "network only" and "injected"](https://github.com/NoahZinsmeister/web3-react/blob/latest/src/connectors/index.ts)

### network only (e.g. accountless Infura/Etherscan API)
[network only in `web3-react`](https://github.com/NoahZinsmeister/web3-react/blob/latest/src/connectors/networkOnly.ts)
[network only in `uniswap-frontend`](https://github.com/Uniswap/uniswap-frontend/blob/beta/src/NetworkOnlyConnector.js)

### injected (e.g. MetaMask)
[injected in `web3-react`](https://github.com/NoahZinsmeister/web3-react/blob/latest/src/connectors/injected.ts)
[injected in `uniswap-frontend`](https://github.com/Uniswap/uniswap-frontend/blob/beta/src/InjectedConnector.js)

It seems that Uniswap ought to be able to pass in minimal config if any to the ones from this lib without too much boilerplate.

Thanks!

**Comment by PaulRBerg** [comment] 2019-11-09 00:21
I chatted with @NoahZinsmeister about this and the issue is that [web3-provider-engine](https://github.com/MetaMask/web3-provider-engine) auto-polls on top of the polling provided by the connectors in `web3-react`.

The custom classes in Uniswap prevent the double polling so that the user's browser doesn't end up making a bajillion network requests.

Of course, this is easy to fix with a configurable flag.

**Comment by NoahZinsmeister** [comment] 2019-11-11 02:56
yes very sorry about this, will be fixed in v6 :)

only recently became aware of this really annoying double-polling behavior

**Comment by NoahZinsmeister** [comment] 2019-11-25 20:27
going to close this, as soon uniswap is [not going to use](https://github.com/Uniswap/uniswap-frontend/pull/514) these custom connectors anymore. the simple augmentations to the current v6 Network and Injected connectors that uniswap _does_ currently implement will likely soon be directly migrated into the v6 connectors.

**Closed by NoahZinsmeister** 2019-11-25 20:27 UTC
Labels: discussion
